/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package form;

import java.awt.Color;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Kariuki
 */
public class mainform extends javax.swing.JFrame {

    /**
     * Creates new form mainform
     */
    public mainform() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg = new javax.swing.JPanel();
        leftside = new javax.swing.JPanel();
        btnupdate = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        btnstock = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        btnremainingstock = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel11 = new javax.swing.JLabel();
        btnprogress = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        midbar = new javax.swing.JPanel();
        stockpanel = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        itemnametxt = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        quantityspinner = new javax.swing.JSpinner();
        jLabel3 = new javax.swing.JLabel();
        costeachtxt = new javax.swing.JTextField();
        totalcosttxt = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        stockpanelbackground = new javax.swing.JLabel();
        updatepanel = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        remaining = new javax.swing.JPanel();
        jPanel11 = new javax.swing.JPanel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        progresspanel = new javax.swing.JPanel();
        jPanel12 = new javax.swing.JPanel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);
        setUndecorated(true);

        bg.setBackground(new java.awt.Color(255, 255, 255));
        bg.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        leftside.setBackground(new java.awt.Color(51, 0, 102));
        leftside.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnupdate.setBackground(new java.awt.Color(51, 0, 122));
        btnupdate.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnupdate.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnupdateMousePressed(evt);
            }
        });

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/form/Available Updates_50px.png"))); // NOI18N

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Update");

        javax.swing.GroupLayout btnupdateLayout = new javax.swing.GroupLayout(btnupdate);
        btnupdate.setLayout(btnupdateLayout);
        btnupdateLayout.setHorizontalGroup(
            btnupdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnupdateLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(27, Short.MAX_VALUE))
        );
        btnupdateLayout.setVerticalGroup(
            btnupdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnupdateLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(btnupdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(btnupdateLayout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        leftside.add(btnupdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 200, 260, -1));

        btnstock.setBackground(new java.awt.Color(65, 65, 118));
        btnstock.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnstock.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnstockMousePressed(evt);
            }
        });

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/form/Add Shopping Cart_48px.png"))); // NOI18N

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Add Stock");

        javax.swing.GroupLayout btnstockLayout = new javax.swing.GroupLayout(btnstock);
        btnstock.setLayout(btnstockLayout);
        btnstockLayout.setHorizontalGroup(
            btnstockLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnstockLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(29, Short.MAX_VALUE))
        );
        btnstockLayout.setVerticalGroup(
            btnstockLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnstockLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(btnstockLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(btnstockLayout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        leftside.add(btnstock, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 140, 260, -1));

        btnremainingstock.setBackground(new java.awt.Color(51, 0, 122));
        btnremainingstock.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnremainingstock.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnremainingstockMousePressed(evt);
            }
        });

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/form/Box_64px.png"))); // NOI18N

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Available Stock");

        javax.swing.GroupLayout btnremainingstockLayout = new javax.swing.GroupLayout(btnremainingstock);
        btnremainingstock.setLayout(btnremainingstockLayout);
        btnremainingstockLayout.setHorizontalGroup(
            btnremainingstockLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnremainingstockLayout.createSequentialGroup()
                .addGap(2, 2, 2)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(21, Short.MAX_VALUE))
        );
        btnremainingstockLayout.setVerticalGroup(
            btnremainingstockLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnremainingstockLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(btnremainingstockLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        leftside.add(btnremainingstock, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 260, 260, 70));

        jLabel10.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 36)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel10.setText("Beauty Shop");
        leftside.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 200, 40));
        leftside.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 240, 10));

        jLabel11.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 36)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel11.setText("Sonnie's ");
        leftside.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 200, 30));

        btnprogress.setBackground(new java.awt.Color(51, 0, 122));
        btnprogress.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnprogress.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnprogressMousePressed(evt);
            }
        });

        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/form/Bullish_48px.png"))); // NOI18N

        jLabel19.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel19.setText("Progress");

        javax.swing.GroupLayout btnprogressLayout = new javax.swing.GroupLayout(btnprogress);
        btnprogress.setLayout(btnprogressLayout);
        btnprogressLayout.setHorizontalGroup(
            btnprogressLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnprogressLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel18)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(29, Short.MAX_VALUE))
        );
        btnprogressLayout.setVerticalGroup(
            btnprogressLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnprogressLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(btnprogressLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel19, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(btnprogressLayout.createSequentialGroup()
                        .addComponent(jLabel18)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        leftside.add(btnprogress, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 330, 260, -1));

        bg.add(leftside, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 560));

        midbar.setBackground(new java.awt.Color(255, 255, 255));
        midbar.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 0, 153), 1, true));
        midbar.setLayout(new java.awt.CardLayout());

        stockpanel.setBackground(new java.awt.Color(255, 255, 255));
        stockpanel.setMaximumSize(new java.awt.Dimension(720, 480));
        stockpanel.setMinimumSize(new java.awt.Dimension(720, 480));
        stockpanel.setName(""); // NOI18N
        stockpanel.setPreferredSize(new java.awt.Dimension(720, 480));
        stockpanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel8.setBackground(new java.awt.Color(102, 51, 255));

        jLabel16.setBackground(new java.awt.Color(102, 51, 255));
        jLabel16.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("Re-Stock");

        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/form/Add Shopping Cart_96px_1.png"))); // NOI18N

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 385, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(219, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 21, Short.MAX_VALUE))
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        stockpanel.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(102, 51, 255));
        jLabel12.setText("Item Name:");
        stockpanel.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, 70, 26));
        stockpanel.add(itemnametxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 180, 180, 26));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(102, 51, 255));
        jLabel2.setText("Cost for each:");
        stockpanel.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 260, 90, 26));

        quantityspinner.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                quantityspinnerKeyTyped(evt);
            }
        });
        stockpanel.add(quantityspinner, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 220, 50, 26));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(102, 51, 255));
        jLabel3.setText("Quantity:");
        stockpanel.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 220, 70, 26));

        costeachtxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                costeachtxtActionPerformed(evt);
            }
        });
        costeachtxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                costeachtxtKeyTyped(evt);
            }
            public void keyPressed(java.awt.event.KeyEvent evt) {
                costeachtxtKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                costeachtxtKeyReleased(evt);
            }
        });
        stockpanel.add(costeachtxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 260, 100, 26));

        totalcosttxt.setEditable(false);
        totalcosttxt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                totalcosttxtMousePressed(evt);
            }
        });
        totalcosttxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                totalcosttxtActionPerformed(evt);
            }
        });
        totalcosttxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                totalcosttxtKeyTyped(evt);
            }
        });
        stockpanel.add(totalcosttxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 300, 100, 26));

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(102, 51, 255));
        jLabel13.setText("Total Cost:");
        stockpanel.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 300, 90, 26));

        stockpanelbackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/form/Capture.PNG"))); // NOI18N
        stockpanelbackground.setMaximumSize(new java.awt.Dimension(718, 378));
        stockpanelbackground.setMinimumSize(new java.awt.Dimension(718, 378));
        stockpanelbackground.setPreferredSize(new java.awt.Dimension(718, 378));
        stockpanel.add(stockpanelbackground, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 138, -1, 340));

        midbar.add(stockpanel, "card2");

        updatepanel.setBackground(new java.awt.Color(255, 255, 255));
        updatepanel.setMaximumSize(new java.awt.Dimension(720, 480));
        updatepanel.setMinimumSize(new java.awt.Dimension(720, 480));
        updatepanel.setPreferredSize(new java.awt.Dimension(720, 480));
        updatepanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel10.setBackground(new java.awt.Color(102, 51, 255));

        jLabel22.setBackground(new java.awt.Color(102, 51, 255));
        jLabel22.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(255, 255, 255));
        jLabel22.setText("Update");

        jLabel23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/form/Available Updates_96px.png"))); // NOI18N

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel10Layout.createSequentialGroup()
                .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 385, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(219, Short.MAX_VALUE))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 21, Short.MAX_VALUE))
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        updatepanel.add(jPanel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/form/Capture.PNG"))); // NOI18N
        jLabel14.setMaximumSize(new java.awt.Dimension(718, 378));
        jLabel14.setMinimumSize(new java.awt.Dimension(718, 378));
        jLabel14.setPreferredSize(new java.awt.Dimension(718, 378));
        updatepanel.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 138, -1, 340));

        midbar.add(updatepanel, "card2");

        remaining.setBackground(new java.awt.Color(255, 255, 255));
        remaining.setMaximumSize(new java.awt.Dimension(720, 480));
        remaining.setMinimumSize(new java.awt.Dimension(720, 480));
        remaining.setPreferredSize(new java.awt.Dimension(720, 480));
        remaining.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel11.setBackground(new java.awt.Color(102, 51, 255));

        jLabel24.setBackground(new java.awt.Color(102, 51, 255));
        jLabel24.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(255, 255, 255));
        jLabel24.setText("Available Stock");

        jLabel25.setIcon(new javax.swing.ImageIcon(getClass().getResource("/form/Box_96px_1.png"))); // NOI18N

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel11Layout.createSequentialGroup()
                .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 385, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(219, Short.MAX_VALUE))
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 21, Short.MAX_VALUE))
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        remaining.add(jPanel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/form/Capture.PNG"))); // NOI18N
        jLabel15.setMaximumSize(new java.awt.Dimension(718, 378));
        jLabel15.setMinimumSize(new java.awt.Dimension(718, 378));
        jLabel15.setPreferredSize(new java.awt.Dimension(718, 378));
        remaining.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 138, -1, 340));

        midbar.add(remaining, "card2");

        progresspanel.setBackground(new java.awt.Color(255, 255, 255));
        progresspanel.setMaximumSize(new java.awt.Dimension(720, 480));
        progresspanel.setMinimumSize(new java.awt.Dimension(720, 480));
        progresspanel.setPreferredSize(new java.awt.Dimension(720, 480));
        progresspanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel12.setBackground(new java.awt.Color(102, 51, 255));

        jLabel26.setBackground(new java.awt.Color(102, 51, 255));
        jLabel26.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(255, 255, 255));
        jLabel26.setText("Progress");

        jLabel27.setIcon(new javax.swing.ImageIcon(getClass().getResource("/form/Bullish_96px_1.png"))); // NOI18N

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel12Layout.createSequentialGroup()
                .addComponent(jLabel27, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, 385, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(219, Short.MAX_VALUE))
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addComponent(jLabel27, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 21, Short.MAX_VALUE))
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        progresspanel.add(jPanel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jLabel28.setIcon(new javax.swing.ImageIcon(getClass().getResource("/form/Capture.PNG"))); // NOI18N
        jLabel28.setMaximumSize(new java.awt.Dimension(718, 378));
        jLabel28.setMinimumSize(new java.awt.Dimension(718, 378));
        jLabel28.setPreferredSize(new java.awt.Dimension(718, 378));
        progresspanel.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 138, -1, 340));

        midbar.add(progresspanel, "card2");

        bg.add(midbar, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 83, 720, 480));

        jLabel1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 0, 102));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("X");
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel1MousePressed(evt);
            }
        });
        bg.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 0, 30, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MousePressed
        System.exit(0);
    }//GEN-LAST:event_jLabel1MousePressed

    private void btnstockMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnstockMousePressed
        setcolor(btnstock);
        resetcolor(btnupdate);
        resetcolor(btnremainingstock);
        resetcolor(btnprogress);
        stockpanel.setVisible(true);
        updatepanel.setVisible(false);
        remaining.setVisible(false);
        progresspanel.setVisible(false);
    }//GEN-LAST:event_btnstockMousePressed

    private void btnremainingstockMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnremainingstockMousePressed
        setcolor(btnremainingstock);
        resetcolor(btnstock);
        resetcolor(btnupdate);
        resetcolor(btnprogress);
        stockpanel.setVisible(false);
        updatepanel.setVisible(false);
        remaining.setVisible(true);
        progresspanel.setVisible(false);
    }//GEN-LAST:event_btnremainingstockMousePressed

    private void btnupdateMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnupdateMousePressed
        setcolor(btnupdate);
        resetcolor(btnstock);
        resetcolor(btnremainingstock);
        resetcolor(btnprogress);
        stockpanel.setVisible(false);
        updatepanel.setVisible(true);
        remaining.setVisible(false);
        progresspanel.setVisible(false);
    }//GEN-LAST:event_btnupdateMousePressed

    private void btnprogressMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnprogressMousePressed
        setcolor(btnprogress);
        resetcolor(btnupdate);
        resetcolor(btnstock);
        resetcolor(btnremainingstock);
        stockpanel.setVisible(false);
        updatepanel.setVisible(false);
        remaining.setVisible(false);
        progresspanel.setVisible(true);
    }//GEN-LAST:event_btnprogressMousePressed

    private void costeachtxtKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_costeachtxtKeyTyped
        if (!(Character.isDigit(evt.getKeyChar()))) {
            evt.consume();
        }            // TODO add your handling code here:
    }//GEN-LAST:event_costeachtxtKeyTyped

    private void totalcosttxtKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_totalcosttxtKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_totalcosttxtKeyTyped

    private void costeachtxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_costeachtxtActionPerformed

    }//GEN-LAST:event_costeachtxtActionPerformed

    private void totalcosttxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_totalcosttxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_totalcosttxtActionPerformed

    private void costeachtxtKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_costeachtxtKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_costeachtxtKeyPressed

    private void totalcosttxtMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_totalcosttxtMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_totalcosttxtMousePressed

    private void costeachtxtKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_costeachtxtKeyReleased
        if (Integer.parseInt(quantityspinner.getValue().toString()) > 0) {
            int quantity = Integer.parseInt(quantityspinner.getValue().toString());
            int eachcost = Integer.parseInt(costeachtxt.getText());
            int total = quantity * eachcost;
            totalcosttxt.setText(String.valueOf(total));
        } else {
            JOptionPane.showMessageDialog(null, "Adjust the quantity to a valid value");
            costeachtxt.setText("");
            totalcosttxt.setText("");
        }   // TODO add your handling code here:
    }//GEN-LAST:event_costeachtxtKeyReleased

    private void quantityspinnerKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_quantityspinnerKeyTyped
        if (!(Character.isDigit(evt.getKeyChar()))) {
            evt.consume();
        }         // TODO add your handling code here:
    }//GEN-LAST:event_quantityspinnerKeyTyped
    void setcolor(JPanel panel) {
        panel.setBackground(new Color(65, 65, 118));
    }

    void resetcolor(JPanel panel) {
        panel.setBackground(new Color(51, 0, 122));
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(mainform.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(mainform.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(mainform.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(mainform.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new mainform().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bg;
    private javax.swing.JPanel btnprogress;
    private javax.swing.JPanel btnremainingstock;
    private javax.swing.JPanel btnstock;
    private javax.swing.JPanel btnupdate;
    private javax.swing.JTextField costeachtxt;
    private javax.swing.JTextField itemnametxt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JPanel leftside;
    private javax.swing.JPanel midbar;
    private javax.swing.JPanel progresspanel;
    private javax.swing.JSpinner quantityspinner;
    private javax.swing.JPanel remaining;
    private javax.swing.JPanel stockpanel;
    private javax.swing.JLabel stockpanelbackground;
    private javax.swing.JTextField totalcosttxt;
    private javax.swing.JPanel updatepanel;
    // End of variables declaration//GEN-END:variables
}
